title: Aurea Flocela Maldonado
logo: /assets/portrait-github.png
description: "Seeking C++ development.<br><br>
  <a href=https://www.linkedin.com/in/flocela-maldonado/>linkedin.com/in/flocela-maldonado</a>"
show_downloads: false

theme: jekyll-theme-minimal
