title: Aurea Flocela Maldonado
logo: /assets/portrait-github.png
description: |
  Seeking C++ development work.
  <a href=https://www.linkedin.com/in/flocela-maldonado/>Linkedin2</a>
show_downloads: false

theme: jekyll-theme-minimal
