title: Aurea Flocela Maldonado
logo: /assets/portrait-github.png
description: >
  Seeking C++ development work.
  <a/></a>
  <a href=https://www.linkedin.com/in/flocela-maldonado/>linkedin.com/in/flocela-maldonado5</a>
show_downloads: false

theme: jekyll-theme-minimal
