title: Aurea Flocela Maldonado
logo: /assets/portrait-github.png
description: "Seeking C++ development work. \
  small line \
  <a href=https://www.linkedin.com/in/flocela-maldonado/>linkedin.com/in/flocela-maldonado7</a>"
show_downloads: false

theme: jekyll-theme-minimal
