title: Aurea Flocela Maldonado
logo: /assets/portrait-github.png
description: |
  Seeking C++ development work.\n
  Seeking C++ development workTesting2.
#[linkedin.com/in/flocela-maldonado](https://www.linkedin.com/in/flocela-maldonado/)
show_downloads: false

theme: jekyll-theme-minimal
