title: Aurea Flocela Maldonado
logo: /assets/portrait-github.png
description: |
  Seeking C++ development work.
  "[test1](https://www.linkedin.com/in/flocela-maldonado/)"
show_downloads: false

theme: jekyll-theme-minimal
